# Generated by Django 5.0.6 on 2024-10-17 09:22

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('popular-philosophers', 'فلاسفه معروف'), ('psychology', 'سبک زندگی و روانشناسی'), ('books', 'کتاب ها'), ('history', 'سیاست و تاریخ'), ('philosophical', 'فلسفی')], default='philosophical', max_length=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 17, 9, 22, 17, 491971, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
    ]
