# Generated by Django 5.0.6 on 2024-10-21 16:54

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وبسایت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('psychology', 'سبک زندگی و روانشناسی'), ('books', 'کتاب ها'), ('philosophical', 'فلسفی'), ('popular-philosophers', 'فلاسفه معروف'), ('history', 'سیاست و تاریخ')], default='philosophical', max_length=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 21, 16, 54, 19, 422957, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='بیو'),
        ),
    ]
