# Generated by Django 5.0.6 on 2024-10-21 17:07

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_instagram_user_telegram_user_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('popular-philosophers', 'فلاسفه معروف'), ('history', 'سیاست و تاریخ'), ('philosophical', 'فلسفی'), ('psychology', 'سبک زندگی و روانشناسی'), ('books', 'کتاب ها')], default='philosophical', max_length=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 21, 17, 7, 26, 987771, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='وبسایت'),
        ),
    ]
